############################################################
#
# Home Assistant Binary Sensors
#
############################################################

# - platform: rest
#   name: Particle relay reduced heating
#   resource: !secret particle_relay1_url
#   method: GET
#   value_template: '{{ value_json.result }}'
#   headers:
#     User-Agent: Home Assistant
#     Content-Type: application/json

# - platform: ping
#   host: 10.254.2.128
#   name: Nintendo Switch

# - platform: trend
#   sensors:
#     bathroom_humidity_falling:
#       entity_id: sensor.bathroom_humidity
#       friendly_name: Bathroom humidity falling
#       sample_duration: 7200
#       min_gradient: -0.00138
#     bathroom_humidity_rising:
#       entity_id: sensor.bathroom_humidity
#       friendly_name: Bathroom humidity rising
#       sample_duration: 7200
#       min_gradient: 0.005556
#       device_class: moisture

# - platform: template
#   sensors:
#     daylight_office:
#       friendly_name: Daylight in Office
#       device_class: light
#       value_template: "{{ states('sensor.office_motion_sensor_1_light_level')|float > 200 }}"
#     daylight_kitchen:
#       friendly_name: Daylight in Kitchen
#       device_class: light
#       value_template: "{{ states('sensor.kitchen_motion_sensor_1_light_level')|float > 200 }}"
#     daylight_bedroom:
#       friendly_name: Daylight in Bedroom
#       device_class: light
#       value_template: "{{ states('sensor.bedroom_motion_sensor_1_light_level')|float > 200 }}"

# - platform: flic

- platform: threshold # will switch state not at 0°C/min but 0.1°C/min or -0.1°C/min depending on the current state of the sensor, respectively
  entity_id: sensor.office_light_level_change_per_hour
  upper: 0
  hysteresis: 0.1 # sensor
  name: Office light level rising
- platform: threshold # will switch state not at 0°C/min but 0.1°C/min or -0.1°C/min depending on the current state of the sensor, respectively
  entity_id: sensor.kitchen_light_level_change_per_hour
  upper: 0
  hysteresis: 0.1 # sensor
  name: Kitchen light level rising
- platform: threshold # will switch state not at 0°C/min but 0.1°C/min or -0.1°C/min depending on the current state of the sensor, respectively
  entity_id: sensor.bedroom_light_level_change_per_hour
  upper: 0
  hysteresis: 0.1 # sensor
  name: Bedroom light level rising
