homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Copenhagen
  customize: !include customize.yaml
  packages: !include_dir_named packages
  external_url: !secret external_url

# Show links to resources in log and frontend
#introduction:

api:

system_health:

# Enables the frontend
frontend:
  themes: !include themes.yaml
  
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  # depricated
  # base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.7.10
    - 192.168.7.1
    - 192.168.7.2
    - 172.30.0.0/16
  #  - 172.16.2.1
  #  - 127.0.0.1
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
    - https://www.home-assistant.io
  # trusted_networks:
  #   - 127.0.0.1
  #   - ::1
  #ip_ban_enabled: True
  #login_attempts_threshold: 5

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:
#  ignore:
#    - philips_hue
#  enable:
#    - homekit

person:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:
  use_include_order: true
  exclude:
    domains:
      - script
      - weblink
      - updater
      - homekit
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.time
      - sensor.time_utc
      - sensor.time_date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.internet_time
      - sensor.henriks_iphone_battery_state
      - sensor.henriks_ipad_battery_state
      - sensor.smappee_power
      - sensor.smappee_usage_today
      - sensor.smappee_fase_1_power
      - sensor.smappee_fase_2_power
      - sensor.smappee_fase_3_power
      - sensor.henriks_iphone_bssid

# history_graph:
#   energy_today:
#     entities:
#       - sensor.smappee_power
#       - sensor.smappee_fase_1_power
#       - sensor.smappee_fase_2_power
#       - sensor.smappee_fase_3_power
#   temperature:
#     entities:
#       - sensor.bedroom_motion_sensor_1
#       - sensor.entrance_motion_sensor_1
#       - sensor.kitchen_motion_sensor_1_2


#influxdb:
#  host: 127.0.0.1
#  database: home_assistant
#  username: !secret influxdb_username
#  password: !secret influxdb_password
#  ssl: true
#  verify_ssl: false
#  default_measurement: state
#  blacklist:
#    - entity.id1
#    - entity.id2
#  whitelist:
#    - entity.id3
#    - entity.id4
#  tags:
#    instance: prod
#    source: hass

# influxdb:
#   host: !secret influxdb_host
#   port: 8086
#   database: home_assistant
#   username: !secret influxdb_username
#   password: !secret influxdb_password
#   max_retries: 3
#   default_measurement: state
#   tags:
#     source: hass

# panel_iframe:
#   grafana:
#     title: Grafana
#     icon: mdi:chart-timeline
#     url: !secret grafana_url
#   influxdb:
#     title: Chronograf
#     icon: mdi:chart-areaspline
#     url: !secret influxdb_url

#prometheus:

# The recorder component is storing details in a database which then are handled by the history component.
recorder:
  db_url: !secret db_url
  exclude:
    domains:
      - weblink
      - updater
      - homekit
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_utc
      - sensor.time_date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.internet_time
      - sensor.henriks_iphone_battery_state
      - sensor.henriks_ipad_battery_state
      - sensor.henriks_iphone_bssid

# View all events in a logbook
logbook:
  exclude:
    domains:
      - weblink
      - updater
      - light
      - homekit
      - timer
    entities:
      - sensor.date
      - sensor.time
      - sensor.time_utc
      - sensor.time_date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc
      - sensor.internet_time
      - sensor.henriks_iphone_battery_state
      - sensor.henriks_ipad_battery_state
      - sensor.smappee_power
      - sensor.smappee_usage_today
      - sensor.smappee_fase_1_power
      - sensor.smappee_fase_2_power
      - sensor.smappee_fase_3_power
      - input_boolean.office_motion
      - input_boolean.bedroom_motion
      - input_boolean.kitchen_motion
      - input_boolean.entrance_motion
      - binary_sensor.office_motion_sensor_1_motion
      - binary_sensor.kitchen_motion_sensor_1_motion
      - binary_sensor.bedroom_motion_sensor_1_motion
      - binary_sensor.entrance_motion_sensor_1_motion
      - binary_sensor.entrance_motion_sensor_2_motion
      - automation.motion_in_bedroom
      - automation.motion_in_bedroom_timer
      - automation.motion_in_entrance
      - automation.motion_in_entrance_timer
      - automation.motion_in_kitchen
      - automation.motion_in_kitchen_timer
      - automation.motion_in_office
      - automation.motion_in_office_timer
      - automation.office_lights_timer_done
      - automation.office_lights_timer_started
      - automation.kitchen_lights_timer_started
      - automation.kitchen_lights_timer_done
      - automation.entrance_lights_timer_done
      - automation.entrance_lights_timer_started
      - sensor.henriks_iphone_bssid


cloud:
zeroconf:
ssdp:
ios:
alexa:
mobile_app:
prometheus:

# Track the sun
sun:

# Text to speech
#tts:
#  #- platform: google
#  - platform: amazon_polly
#    aws_access_key_id: !secret aws_access_key_id
#    aws_secret_access_key: !secret aws_secret_access_key
#    region_name: !secret aws_region_name

wake_on_lan:

ifttt:
  key: !secret ifttt_key

mqtt:
  broker: core-mosquitto
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: homeassistant
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

homekit:
  #auto_start: True
  filter:
    include_domains:
      - script
      - input_boolean
      - switch
      - timer

#tado:
#  username: !secret tado_username
#  password: !secret tado_password

# smappee:
#   host: 192.168.7.116
#   client_id: !secret smappee_client_id
#   client_secret: !secret smappee_client_secret
#   username: !secret smappee_username
#   password: !secret smappee_password

apple_tv:
#  host: 192.168.7.195
#  login_id: !secret apple_tv_login_id
#  credentials: !secret apple_tv_credentials

# logi_circle:
#   client_id: !secret logi_circle_client_id
#   client_secret: !secret logi_circle_client_secret
#   api_key: !secret logi_circle_api_key
#   redirect_uri: !secret logi_circle_redirect_url

#nest:
#  client_id: !secret nest_client_id
#  client_secret: !secret nest_client_secret

nissan_leaf:
  username: !secret nissan_leaf_username
  password: !secret nissan_leaf_password
  region: !secret nissan_leaf_region

roomba:
  - host: !secret roomba_host
    blid: !secret roomba_username
    password: !secret roomba_password

withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret
  use_webhook: true
  #profiles:
  #  - !secret withings_profile1

plex:
  host: !secret plex_host
  port: 32400
  token: !secret plex_token
  ssl: true
  verify_ssl: false
  media_player:
    use_episode_art: true

#hue:
#  bridges:
#    - host: 192.168.7.105
#      allow_hue_groups: true

webostv:
  host: 192.168.7.14
  name: LG OLED
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret lg_oled_wifi_mac
  customize:
    sources:
    - Apple TV
    - PS5
    - HDMI4
    - Netflix
    - YouTube
    - Plex

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

#tradfri:
#  host: 192.168.7.102

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

#cast:
stream:

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

# rest_command:
#   particle_relay1_on:
#     url: !secret particle_relay_post_url
#     method: post
#     payload: '{ "arg": "relay1:on" }'
#     timeout: 5
#     content_type: 'application/json'
#   particle_relay1_off:
#     url: !secret particle_relay_post_url
#     method: post
#     payload: '{ "arg": "relay1:off" }'
#     timeout: 5
#     content_type: 'application/json'

timer:
  sleep:
    duration: '00:30:00'
    icon: mdi:sleep
  entrance_lights:
    duration: '00:05:00'
    icon: mdi:lightbulb-on
  kitchen_lights:
    duration: '00:05:00'
    icon: mdi:lightbulb-on
  bedroom_lights:
    duration: '00:05:00'
    icon: mdi:lightbulb-on
  office_lights:
    duration: '00:05:00'
    icon: mdi:lightbulb-on
  fan_direction_timer:
    duration: '01:00:00'
    icon: mdi:fan
  fan_speed_timer:
    duration: '01:00:00'
    icon: mdi:fan
  fan_power_timer:
    duration: '00:30:00'
    icon: mdi:fan

logger:
  #default: debug
  #default: info
  default: warning
  logs:
    # log level for the `aiohttp` Python package
    #aiohttp: debug
    #urllib3: debug
    # http debug
    #homeassistant.components.http: debug
    #custom_components.media_player.ps4: debug
    #homeassistant.components.smappee: error
    #homeassistant.components.mqtt: error
    #homeassistant.deconz: debug
    #homeassistant.components.deconz: debug
    #pydeconz: debug
    #py.warnings: error
    #pyps4: debug
    #smappy: debug
    #pyps4.connection: debug
    #pylgtv.webos_client: critical
    #aiounifi: debug
    #homeassistant.components.unifi: debug
    #homeassistant.components.switch.unifi: debug
    #homeassistant.components.nissan_leaf: debug
    #homeassistant.components.device_tracker.nissan_leaf: debug
    #homeassistant.components.sensor.nissan_leaf: debug
    #homeassistant.components.switch.nissan_leaf: debug
    homeassistant.components.shell_command: debug

light: !include light.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
fan: !include fans.yaml
device_tracker: !include device_trackers.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
media_player: !include media_players.yaml
notify: !include notify.yaml
image_processing: !include image_processing.yaml
switch: !include_dir_merge_list switches
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
zone: !include zones.yaml

template:
  - sensor:
      - name: "Humidity difference"
        unit_of_measurement: "%"
        state: >
          {% set bedroom = states('sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity') | float %}
          {% set outdoor = states('sensor.netatmo_ewaldsvej_kokken_outdoor_humidity') | float %}

          {{ (bedroom - outdoor) | round(1) }}

#python_script:

shell_command:
  #livingroom_fan_speed: echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x04\x03\x0d\x0a' | nc -w 1 -u -n 192.168.7.248 4000
  #livingroom_fan_status: python custom_scripts/fan_control.py --ip 192.168.7.248 --command status --print power
  #livingroom_fan_power: python custom_scripts/fan_control.py --ip 192.168.7.248 --command power --print power
  bedroom_fan_speed: python3 custom_scripts/fan_control.py --ip 192.168.7.249 --command speed --speed {{speed}} --print speed
  bedroom_fan_direction: python3 custom_scripts/fan_control.py --ip 192.168.7.249 --command direction --direction {{direction}} --print direction
  livingroom_fan_speed: python3 custom_scripts/fan_control.py --ip 192.168.7.248 --command speed --speed {{speed}} --print speed
  livingroom_fan_direction: python3 custom_scripts/fan_control.py --ip 192.168.7.248 --command direction --direction {{direction}} --print direction
  #livingroom_fan_speed_var: echo -n -e '\x6d\x6f\x62\x69\x6c\x65\x04\x'{{speed}}'\x0d\x0a' | nc -w 1 -u -n 192.168.7.248 4000

#zwave:
#  usb_path: /dev/ttyACM0
#  network_key: !secret zwave_network_key
#  debug: True

automation: !include automations.yaml
automation old: !include_dir_merge_list automation
