- platform: group
  name: Kitchen lights
  entities:
    - light.kitchen
    # - light.kitchen_spot_1_1
    # - light.kitchen_spot_2_1
    # - light.kitchen_spot_3_1
    # - light.kitchen_spot_1_2
    # - light.kitchen_spot_2_2
    # - light.kitchen_spot_3_2

- platform: group
  name: Entrance lights
  entities:
    - light.entrance
    # - light.entrance_lamp_1
    # - light.entrance_spot_1
    # - light.entrance_spot_2
    # - light.entrance_spot_3
    # - light.entrance_lamp_room

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom
    #- light.hue_ambiance_ceiling_bedroom

- platform: group
  name: Office lights
  entities:
    - light.office
    #- light.artemide_lamp

- platform: group
  name: Cinema lights
  entities:
    - light.cinema
    #- light.living_room_table
    #- light.binic
    #- light.artemide_lamp

- platform: group
  name: Living room lights
  entities:
    - light.living_room


- platform: group
  name: All lights
  entities:
    - light.living_room
    - light.office
    - light.cinema
    - light.bedroom
    - light.entrance
    - light.kitchen

# - platform: switch
#   name: Office Artemide
#   entity_id: switch.artemide_switch

#- platform: flux_led
#  devices:
#    10.254.2.178:
#      name: stairs
#      mode: "rgb"
#      protocol: ledenet
