- platform: syslog
  name: syslog

- platform: smtp
  name: email
  server: email-smtp.eu-west-1.amazonaws.com
  port: 465
  username: !secret smtp_username
  password: !secret smtp_password
  starttls: true
  sender: !secret notify_email_sender
  recipient: !secret notify_email_recipient

- platform: html5
  name: HTML5
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email

#- platform: webostv
#  host: 192.168.8.197
#  name: tv

- platform: group
  name: ALL_DEVICES
  services:
    - service: mobile_app_henriks_iphone
    - service: mobile_app_henriks_ipad
    - service: mobile_app_hmnmbp

- platform: group
  name: all
  services:
    - service: syslog
    - service: html5
    - service: tv
    - service: app
    - service: smtp
