- platform: syslog
  name: syslog

#- platform: smtp
#  name: email
#  server: smtp.gmail.com
#  port: 587
#  username: !secret smtp_username
#  password: !secret smtp_password
#  starttls: true
#  sender: !secret notify_email_sender
#  recipient: !secret notify_email_recipient

- platform: html5
  name: HTML5
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email

- platform: webostv
  host: 10.254.2.118
  name: tv

- platform: ios
  name: app
  target: !secret notify_ios_target

- platform: group
  name: all
  services:
    - service: syslog
    - service: html5
    - service: tv
    - service: app
