- platform: statistics
  name: "Bathroom humidity mean over last 24 hours"
  entity_id: sensor.4_in_1_multisensor_humidity
  state_characteristic: mean
  max_age:
    hours: 24
  sampling_size: 50
  precision: 1

- platform: statistics
  name: "Bathroom humidity change over 1 hour"
  entity_id: sensor.4_in_1_multisensor_humidity
  state_characteristic: change
  max_age:
    minutes: 60
  sampling_size: 50
  precision: 1

- platform: statistics
  name: "Bathroom humidity median over last 24 hours"
  entity_id: sensor.4_in_1_multisensor_humidity
  state_characteristic: median
  max_age:
    hours: 24
  sampling_size: 50
  precision: 1

- platform: statistics
  name: "Bathroom humidity over last 24 hours"
  entity_id: sensor.4_in_1_multisensor_humidity
  state_characteristic: average_linear
  max_age:
    hours: 24
  sampling_size: 50
  precision: 1
