# power conversion
# https://www.home-assistant.io/integrations/integration/#energy
- platform: integration
  source: sensor.smappee_power
  name: Energy spent
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.smappee_server_power
  name: Server spent
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.smappee_cinema_power
  name: Cinema spent
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.car_charger_power
  name: Car charger spent
  unit_prefix: k
  round: 2

# - platform: min_max
#   round_digits: 0
#   name: Smappee power (min/max)
#   entity_ids:
#     - sensor.smappee_power

# usage
# - platform: statistics
#   entity_id: sensor.smappee_power
#   name: Smappee power statistics
#   max_age:
#     days: 7
#   state_characteristic: mean

# eloverblik
- platform: statistics
  entity_id: sensor.eloverblik_energy_total
  name: Eloverblik Monthly Statistics
  max_age:
      days: 30
  state_characteristic: mean

# nordpool
# - platform: nordpool

#   # Should the prices include vat? Default True
#   VAT: True

#   # What currency the api fetches the prices in
#   # this is only need if you want a sensor in a non local currecy
#   currency: "DKK"

#   # Helper so you can set your "low" price
#   # low_price = hour_price < average * low_price_cutoff
#   low_price_cutoff: 0.95

#   # What power regions your are interested in.
#   # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
#   region: "DK1"

#   # How many decimals to use in the display of the price
#   precision: 3

#   # What the price should be displayed in default
#   # Possible values: MWh, kWh and Wh
#   # default: kWh
#   price_type: kWh

#   # This option allows the usage of a template to add a tariff.
#   # now() always refers start of the hour of that price.
#   # this way we can calculate the correct costs add that to graphs etc.
#   # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
#   # default {{0.0|float}}
#   #additional_costs: "{{0.0|float}}"
