# power conversion
# https://www.home-assistant.io/integrations/integration/#energy
- platform: integration
  source: sensor.smappee_power
  name: Energy spent
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.smappee_server_power
  name: Server spent
  unit_prefix: k
  round: 2

- platform: integration
  source: sensor.smappee_cinema_power
  name: Cinema spent
  unit_prefix: k
  round: 2

# - platform: min_max
#   round_digits: 0
#   name: Smappee power (min/max)
#   entity_ids:
#     - sensor.smappee_power

# usage
# - platform: statistics
#   entity_id: sensor.smappee_power
#   name: Smappee power statistics
#   max_age:
#     days: 7
#   state_characteristic: mean

# eloverblik
- platform: statistics
  entity_id: sensor.eloverblik_energy_total
  name: Eloverblik Monthly Statistics
  max_age:
      days: 30
  state_characteristic: mean

# nordpool
- platform: nordpool

  # Should the prices include vat? Default True
  VAT: True

  # What currency the api fetches the prices in
  # this is only need if you want a sensor in a non local currecy
  currency: "DKK"

  # Helper so you can set your "low" price
  # low_price = hour_price < average * low_price_cutoff
  low_price_cutoff: 0.95

  # What power regions your are interested in.
  # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
  region: "DK1"

  # How many decimals to use in the display of the price
  precision: 3

  # What the price should be displayed in default
  # Possible values: MWh, kWh and Wh
  # default: kWh
  price_type: kWh

  # This option allows the usage of a template to add a tariff.
  # now() always refers start of the hour of that price.
  # this way we can calculate the correct costs add that to graphs etc.
  # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
  # default {{0.0|float}}
  #additional_costs: "{{0.0|float}}"

- platform: template
  sensors:
    nordpool_today_hr_00_01:
      friendly_name: NordPool today h 01
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[0] }}'
    nordpool_today_hr_01_02:
      friendly_name: NordPool today h 02
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[1] }}'
    nordpool_today_hr_02_03:
      friendly_name: NordPool today h 03
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[2] }}'
    nordpool_today_hr_03_04:
      friendly_name: NordPool today h 04
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[3] }}'
    nordpool_today_hr_04_05:
      friendly_name: NordPool today h 05
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[4] }}'
    nordpool_today_hr_05_06:
      friendly_name: NordPool today h 06
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[5] }}'
    nordpool_today_hr_06_07:
      friendly_name: NordPool today h 07
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[6] }}'
    nordpool_today_hr_07_08:
      friendly_name: NordPool today h 08
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[7] }}'
    nordpool_today_hr_08_09:
      friendly_name: NordPool today h 09
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[8] }}'
    nordpool_today_hr_09_10:
      friendly_name: NordPool today h 10
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[9] }}'
    nordpool_today_hr_10_11:
      friendly_name: NordPool today h 11
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[10] }}'
    nordpool_today_hr_11_12:
      friendly_name: NordPool today h 12
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[11] }}'
    nordpool_today_hr_12_13:
      friendly_name: NordPool today h 13
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[12] }}'
    nordpool_today_hr_13_14:
      friendly_name: NordPool today h 14
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[13] }}'
    nordpool_today_hr_14_15:
      friendly_name: NordPool today h 15
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[14] }}'
    nordpool_today_hr_15_16:
      friendly_name: NordPool today h 16
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[15] }}'
    nordpool_today_hr_16_17:
      friendly_name: NordPool today h 17
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[16] }}'
    nordpool_today_hr_17_18:
      friendly_name: NordPool today h 18
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[17] }}'
    nordpool_today_hr_18_19:
      friendly_name: NordPool today h 19
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[18] }}'
    nordpool_today_hr_19_20:
      friendly_name: NordPool today h 20
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[19] }}'
    nordpool_today_hr_20_21:
      friendly_name: NordPool today h 21
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[20] }}'
    nordpool_today_hr_21_22:
      friendly_name: NordPool today h 22
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[21] }}'
    nordpool_today_hr_22_23:
      friendly_name: NordPool today h 23
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[22] }}'
    nordpool_today_hr_23_24:
      friendly_name: NordPool today h 24
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "today")[23] }}'
    nordpool_tomorrow_hr_00_01:
      friendly_name: NordPool tomorrow h 01
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[0] }}'
    nordpool_tomorrow_hr_01_02:
      friendly_name: NordPool tomorrow h 02
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[1] }}'
    nordpool_tomorrow_hr_02_03:
      friendly_name: NordPool tomorrow h 03
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[2] }}'
    nordpool_tomorrow_hr_03_04:
      friendly_name: NordPool tomorrow h 04
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[3] }}'
    nordpool_tomorrow_hr_04_05:
      friendly_name: NordPool tomorrow h 05
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[4] }}'
    nordpool_tomorrow_hr_05_06:
      friendly_name: NordPool tomorrow h 06
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[5] }}'
    nordpool_tomorrow_hr_06_07:
      friendly_name: NordPool tomorrow h 07
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[6] }}'
    nordpool_tomorrow_hr_07_08:
      friendly_name: NordPool tomorrow h 08
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[7] }}'
    nordpool_tomorrow_hr_08_09:
      friendly_name: NordPool tomorrow h 09
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[8] }}'
    nordpool_tomorrow_hr_09_10:
      friendly_name: NordPool tomorrow h 10
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[9] }}'
    nordpool_tomorrow_hr_10_11:
      friendly_name: NordPool tomorrow h 11
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[10] }}'
    nordpool_tomorrow_hr_11_12:
      friendly_name: NordPool tomorrow h 12
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[11] }}'
    nordpool_tomorrow_hr_12_13:
      friendly_name: NordPool tomorrow h 13
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[12] }}'
    nordpool_tomorrow_hr_13_14:
      friendly_name: NordPool tomorrow h 14
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[13] }}'
    nordpool_tomorrow_hr_14_15:
      friendly_name: NordPool tomorrow h 15
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[14] }}'
    nordpool_tomorrow_hr_15_16:
      friendly_name: NordPool tomorrow h 16
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[15] }}'
    nordpool_tomorrow_hr_16_17:
      friendly_name: NordPool tomorrow h 17
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[16] }}'
    nordpool_tomorrow_hr_17_18:
      friendly_name: NordPool tomorrow h 18
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[17] }}'
    nordpool_tomorrow_hr_18_19:
      friendly_name: NordPool tomorrow h 19
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[18] }}'
    nordpool_tomorrow_hr_19_20:
      friendly_name: NordPool tomorrow h 20
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[19] }}'
    nordpool_tomorrow_hr_20_21:
      friendly_name: NordPool tomorrow h 21
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[20] }}'
    nordpool_tomorrow_hr_21_22:
      friendly_name: NordPool tomorrow h 22
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[21] }}'
    nordpool_tomorrow_hr_22_23:
      friendly_name: NordPool tomorrow h 23
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[22] }}'
    nordpool_tomorrow_hr_23_24:
      friendly_name: NordPool tomorrow h 24
      icon_template: mdi:cash
      unit_of_measurement: DKK
      value_template: '{{ state_attr("sensor.nordpool_kwh_dk1_dkk_3_095_025", "tomorrow")[23] }}'

# zaptec

- platform: template
  binary_sensor:
    zaptec_home_firmware_up2date:
      friendly_name: Zaptec home firmware up2date
      icon: mdi:update
      value_template: '{{ state_attr("sensor.zaptec_charger_zap016548", "firmware_update_to_date") }}'

    zaptec_home_warnings:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger warnings"
      icon_template: mdi:alert-circle-outline
      value_template: >-
        {% if is_state_attr('sensor.zaptec_charger_zap016548', 'warnings', '0') %}
          False
        {% else %}
          True
        {% endif %}

  sensors:
    zaptec_home_allocated:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger allocated current"
      icon_template: mdi:waves
      unit_of_measurement: "A"
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'charge_current_set') | round(0) }}"

    zaptec_home_current:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger current"
      icon_template: mdi:current-ac
      unit_of_measurement: "A"
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'current_phase1') | round(0) }}"

    zaptec_home_energy:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger energy"
      icon_template: mdi:counter
      unit_of_measurement: "kWh"
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'total_charge_power_session') | round(0) }}"

    zaptec_home_firmware:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger firmware version"
      icon_template: mdi:label
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'smart_computer_software_application_version') }}"

    zaptec_home_firmware_current:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger Current firmware version"
      icon_template: mdi:label
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'current_firmware_version') }}"

    zaptec_home_firmware_available:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger available firmware version"
      icon_template: mdi:label
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'available_firmware_version') }}"

    zaptec_home_humidity:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger humidity"
      icon_template: mdi:water-percent
      unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'humidity') | round(0) }}"

    zaptec_home_mode:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger mode"
      icon_template: mdi:alpha-z-circle-outline
      value_template: >-
        {% if is_state_attr('sensor.zaptec_charger_zap016548', 'charger_operation_mode', '1') %}
          Disconnected
        {% elif is_state_attr('sensor.zaptec_charger_zap016548', 'charger_operation_mode', '2') %}
          Waiting
        {% elif is_state_attr('sensor.zaptec_charger_zap016548', 'charger_operation_mode', '3') %}
          Charging
        {% elif is_state_attr('sensor.zaptec_charger_zap016548', 'charger_operation_mode', '5') %}
          Finished
        {% else %}
          Unknown
        {% endif %}

    zaptec_home_power:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger power"
      icon_template: mdi:power-plug
      unit_of_measurement: "W"
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'total_charge_power') | round(0) }}"

    zaptec_home_signal:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger signal strength"
      icon_template: >-
        {% if state_attr('sensor.zaptec_charger_zap016548', 'communication_signal_strength') | float >= -67 %}
          mdi:wifi-strength-4
        {% elif state_attr('sensor.zaptec_charger_zap016548', 'communication_signal_strength') | float >= -72 %}
          mdi:wifi-strength-3
        {% elif state_attr('sensor.zaptec_charger_zap016548', 'communication_signal_strength') | float >= -80 %}
          mdi:wifi-strength-2
        {% elif state_attr('sensor.zaptec_charger_zap016548', 'communication_signal_strength') | float >= -90 %}
          mdi:wifi-strength-1
        {% else %}
          mdi:wifi-strength-outline
        {% endif %}
      unit_of_measurement: "dBm"
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'communication_signal_strength') }}"

    zaptec_home_state:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger state"
      icon_template: >-
        {% if is_state_attr('sensor.zaptec_charger_zap016548', 'is_online', '1') %}
          mdi:access-point-network
        {% else %}
          mdi:access-point-network-off
        {% endif %}
      value_template: >-
        {% if is_state_attr('sensor.zaptec_charger_zap016548', 'is_online', '1') %}
          Online
        {% else %}
          Offline
        {% endif %}

    zaptec_home_temperature:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger temperature"
      icon_template: mdi:thermometer
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'temperature_internal5') | round(0) }}"

    zaptec_home_voltage:
      entity_id: sensor.zaptec_charger_zap016548
      friendly_name: "Car charger voltage"
      icon_template: mdi:flash
      unit_of_measurement: "V"
      value_template: "{{ state_attr('sensor.zaptec_charger_zap016548', 'voltage_phase1') | round(0) }}"
