- platform: statistics
  name: Office light statistics
  entity_id: sensor.office_motion_sensor_1_light_level
  #max_age:
  #  minutes: 30
  sampling_size: 10
  #device_class: illuminance
  #state_class: measurement
  state_characteristic: average_linear
- platform: statistics
  name: Kitchen light statistics
  entity_id: sensor.kitchen_motion_sensor_1_light_level
  #max_age:
  #  minutes: 30
  sampling_size: 10
  #device_class: illuminance
  #state_class: measurement
  state_characteristic: average_linear
- platform: statistics
  name: Bedroom light statistics
  entity_id: sensor.bedroom_motion_sensor_1_light_level
  #max_age:
  #  minutes: 30
  sampling_size: 10
  #device_class: illuminance
  #state_class: measurement
  state_characteristic: average_linear
- platform: statistics
  name: Entrance light statistics
  entity_id: sensor.entrance_motion_sensor_2_light_level
  #max_age:
  #  minutes: 30
  sampling_size: 10
  #device_class: illuminance
  #state_class: measurement
  state_characteristic: average_linear

- platform: min_max
  name: Combined light levels
  entity_ids:
    - sensor.office_light_statistics
    - sensor.kitchen_light_statistics
    - sensor.bedroom_light_statistics
  type: mean
  #device_class: illuminance
  #state_class: measurement

# - platform: derivative
#   source: sensor.office_motion_sensor_1_light_level
#   name: Office light level change per hour
#   round: 1
#   unit_time: h # the resulting "unit_of_measurement" will be °C/h if the sensor.temperate has set °C as it's unit
#   time_window: "00:15:00"
# - platform: derivative
#   source: sensor.kitchen_motion_sensor_1_light_level
#   name: Kitchen light level change per hour
#   round: 1
#   unit_time: h # the resulting "unit_of_measurement" will be °C/h if the sensor.temperate has set °C as it's unit
#   time_window: "00:15:00"
# - platform: derivative
#   source: sensor.bedroom_motion_sensor_1_light_level
#   name: Bedroom light level change per hour
#   round: 1
#   unit_time: h # the resulting "unit_of_measurement" will be °C/h if the sensor.temperate has set °C as it's unit
#   time_window: "00:15:00"
