- platform: mqtt
  name: Smappee power
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ value_json.totalPower }}"

- platform: mqtt
  name: Smappee usage today
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "kWh"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.totalImportEnergy | multiply(0.0000001)) | round(2) }}"

- platform: mqtt
  name: Smappee solar today
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "kWh"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.totalExportEnergy | multiply(0.0000001)) | round(2) }}"

- platform: mqtt
  name: Smappee reactive power
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ value_json.totalReactivePower }}"

- platform: mqtt
  name: Smappee voltage
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/realtime"
  unit_of_measurement: "V"
  icon: "mdi:power-plug"
  value_template: "{{ value_json.voltages[0].voltage }}"

- platform: mqtt
  name: Smappee always on
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/aggregated"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.intervalDatas[0].alwaysOn | multiply(0.001)) | round(2) }}"

- platform: mqtt
  name: Smappee average RMS Voltage
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/aggregated"
  unit_of_measurement: "V"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.intervalDatas[0].averageRMSVoltage | multiply(0.1)) | round(2) }}"

- platform: mqtt
  name: Smappee server power
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/aggregatedSwitch"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.switchIntervalDatas[0].activePower | multiply(0.001)) | round(2) }}"

- platform: mqtt
  name: Smappee laptop power
  state_topic: "servicelocation/579acd67-d672-11e7-ac58-022d286959f5/aggregatedSwitch"
  unit_of_measurement: "W"
  icon: "mdi:power-plug"
  value_template: "{{ (value_json.switchIntervalDatas[1].activePower | multiply(0.001)) | round(2) }}"

#
#
# servicelocation/579acd67-d672-11e7-ac58-022d286959f5/aggregated
# {"intervalDatas":[{"utcEndtime":1545659400000,"averageRMSVoltage":2284,"alwaysOn":310102,"channelIntervalDatas":[{"averageRMSCurrent":1099,"averageImportRMSActivePower":222712,"averageExportRMSActivePower":0,"averageRMSApparentPower":251522,"averageRMSReactivePower":116814,"averagePowerfactor":87,"ctInput":0},{"averageRMSCurrent":2030,"averageImportRMSActivePower":424142,"averageExportRMSActivePower":0,"averageRMSApparentPower":464309,"averageRMSReactivePower":188905,"averagePowerfactor":90,"ctInput":1},{"averageRMSCurrent":106,"averageImportRMSActivePower":19551,"averageExportRMSActivePower":0,"averageRMSApparentPower":24460,"averageRMSReactivePower":14681,"averagePowerfactor":77,"ctInput":2}],"version":1}]}
#
#
# servicelocation/579acd67-d672-11e7-ac58-022d286959f5/aggregatedSwitch
# {
#   "switchIntervalDatas":
#     [
#     {
#       "utcEndtime":1545659400000,
#       "activePower":188883,
#       "reactivePower":0,
#       "version":1,
#       "sensorId":1
#     },
#     {
#       "utcEndtime":1545659400000,
#       "activePower":46056,
#       "reactivePower":0,
#       "version":1,
#       "sensorId":2
#     }
#     ]
# }
