- alias: "Bathroom humidity high"
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      minutes: '/15'
      seconds: 00
    - platform: state
      entity_id: binary_sensor.bathroom_humidity_rising
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.bathroom_humidity_rising
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.bathroom_humidity
        above: 75
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_fan

- alias: "Bathroom humidity normal"
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: '/15'
      seconds: 00
    - platform: state
      entity_id: binary_sensor.bathroom_humidity_rising
      to: 'off'
      for:
        minutes: 30
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.bathroom_humidity_rising
        state: 'off'
        for:
          minutes: 30
      - condition: numeric_state
        entity_id: sensor.bathroom_humidity
        below: 40
  action:
    service: switch.turn_off
    entity_id: switch.bathroom_fan

- alias: "Bathroom cold outside"
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_temperature
      below: 15
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_pump

- alias: "Bathroom heating required"
  trigger:
    - platform: numeric_state
      entity_id: sensor.bathroom_heating
      above: 0
  action:
    service: switch.turn_on
    entity_id: switch.bathroom_pump

- alias: "Bathroom heating ok"
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_temperature
      above: 18
    - platform: numeric_state
      entity_id: sensor.bathroom_heating
      below: 1
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.weather_temperature
        above: 18
      - condition: numeric_state
        entity_id: sensor.bathroom_heating
        below: 1
  action:
    service: switch.turn_off
    entity_id: switch.bathroom_pump
