- alias: "Error in Smappee energy data"
  trigger:
    - platform: numeric_state
      entity_id: sensor.smappee_usage_today
      below: 0
    - platform: numeric_state
      entity_id: sensor.smappee_usage_today_raw
      above: 2000000000
    - platform: state
      entity_id: button.smappee_reboot
  action:
    - service: notify.ALL_DEVICES
      data:
        title: "Smappee energy data error"
        message: "Error in data from Smappee, rebooting energy monitor."
    - service: shell_command.smappee_reboot

- alias: "Zaptec home charger firmware update available"
  trigger:
    - platform: state
      entity_id: binary_sensor.car_charger_firmware
      from: "Up-to-date"
  action:
    - service: notify.ALL_DEVICES
      data:
        title: "Zaptec home charger firmware update available"
        message: "Zaptec home charger firmware update available."
        data:
          importance: high
    - service: notify.all
      data:
        message: "Zaptec home charger firmware update available."

- alias: "Zaptec home charger warning"
  trigger:
    - platform: state
      entity_id: binary_sensor.car_charger_warnings
      from: "OK"
  action:
    - service: notify.ALL_DEVICES
      data:
        title: "Zaptec home charger warning"
        message: "Zaptec home charger warning"
        data:
          importance: high
    - service: notify.all
      data:
        message: "Zaptec home charger warning"
