- alias: Set Livingroom fan speed
  trigger:
    platform: state
    entity_id: sensor.livingroom_fan_speed
  action:
    service: input_select.select_option
    entity_id: input_select.livingroom_fan_speed
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Livingroom fan direction
  trigger:
    platform: state
    entity_id: sensor.livingroom_fan_direction
  action:
    service: input_select.select_option
    entity_id: input_select.livingroom_fan_direction
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Bedroom fan speed
  trigger:
    platform: state
    entity_id: sensor.bedroom_fan_speed
  action:
    service: input_select.select_option
    entity_id: input_select.bedroom_fan_speed
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Bedroom fan direction
  trigger:
    platform: state
    entity_id: sensor.bedroom_fan_direction
  action:
    service: input_select.select_option
    entity_id: input_select.bedroom_fan_direction
    data_template:
      option: "{{ trigger.to_state.state }}"


- alias: Livingroom fan speed update
  trigger:
    platform: state
    entity_id: input_select.livingroom_fan_speed
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: shell_command.livingroom_fan_speed
      data_template:
        speed: "{{ trigger.to_state.state }}"

- alias: Livingroom fan direction update
  trigger:
    platform: state
    entity_id: input_select.livingroom_fan_direction
  action:
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: shell_command.livingroom_fan_direction
      data_template:
        direction: "{{ trigger.to_state.state }}"

- alias: Bedroom fan speed update
  trigger:
    platform: state
    entity_id: input_select.bedroom_fan_speed
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: shell_command.bedroom_fan_speed
      data_template:
        speed: "{{ trigger.to_state.state }}"

- alias: Bedroom fan direction update
  trigger:
    platform: state
    entity_id: input_select.bedroom_fan_direction
  action:
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: shell_command.bedroom_fan_direction
      data_template:
        direction: "{{ trigger.to_state.state }}"


- alias: Fan mode set default
  trigger:
    - platform: state
      entity_id: input_select.fan_mode
      to: 'default'
  action:
    - service: timer.start
      entity_id: timer.fan_power_timer
    - service: switch.turn_on
      entity_id: switch.bedroom_fan
    - service: switch.turn_on
      entity_id: switch.livingroom_fan
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'alternating'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_direction
        option: 'alternating'
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '01'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_speed
        option: '01'

- alias: Fan mode set eco
  trigger:
    - platform: state
      entity_id: input_select.fan_mode
      to: 'eco'
  action:
    - service: timer.start
      entity_id: timer.fan_power_timer
    - service: switch.turn_off
      entity_id: switch.bedroom_fan
    - service: switch.turn_on
      entity_id: switch.livingroom_fan
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_direction
        option: 'alternating'
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_speed
        option: '01'

- alias: Fan mode set sleep
  trigger:
    - platform: state
      entity_id: input_select.fan_mode
      to: 'sleep'
  action:
    - service: timer.start
      entity_id: timer.fan_power_timer
    - service: switch.turn_on
      entity_id: switch.bedroom_fan
    - service: switch.turn_off
      entity_id: switch.livingroom_fan
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'alternating'
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '01'

- alias: Fan mode set sleep warm
  trigger:
    - platform: state
      entity_id: input_select.fan_mode
      to: 'sleep warm'
  action:
    - service: timer.start
      entity_id: timer.fan_power_timer
    - service: switch.turn_on
      entity_id: switch.bedroom_fan
    - service: switch.turn_off
      entity_id: switch.livingroom_fan
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'in'
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '01'

- alias: Fan mode set sleep cold
  trigger:
    - platform: state
      entity_id: input_select.fan_mode
      to: 'sleep cold'
  action:
    - service: timer.start
      entity_id: timer.fan_power_timer
    - service: switch.turn_on
      entity_id: switch.bedroom_fan
    - service: switch.turn_off
      entity_id: switch.livingroom_fan
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'out'
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '01'

- alias: Fan mode set off
  trigger:
    - platform: state
      entity_id: input_select.fan_mode
      to: 'off'
  action:
    - service: timer.start
      entity_id: timer.fan_power_timer
    - service: switch.turn_off
      entity_id: switch.bedroom_fan
    - service: switch.turn_off
      entity_id: switch.livingroom_fan
