- alias: Set Livingroom fan speed
  trigger:
    platform: state
    entity_id: sensor.livingroom_fan_speed
  action:
    service: input_select.select_option
    entity_id: input_select.livingroom_fan_speed
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Livingroom fan direction
  trigger:
    platform: state
    entity_id: sensor.livingroom_fan_direction
  action:
    service: input_select.select_option
    entity_id: input_select.livingroom_fan_direction
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Bedroom fan speed
  trigger:
    platform: state
    entity_id: sensor.bedroom_fan_speed
  action:
    service: input_select.select_option
    entity_id: input_select.bedroom_fan_speed
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Bedroom fan direction
  trigger:
    platform: state
    entity_id: sensor.bedroom_fan_direction
  action:
    service: input_select.select_option
    entity_id: input_select.bedroom_fan_direction
    data_template:
      option: "{{ trigger.to_state.state }}"


- alias: Livingroom fan speed update
  trigger:
    platform: state
    entity_id: input_select.livingroom_fan_speed
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: shell_command.livingroom_fan_speed
      data_template:
        speed: "{{ trigger.to_state.state }}"

- alias: Livingroom fan direction update
  trigger:
    platform: state
    entity_id: input_select.livingroom_fan_direction
  action:
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: shell_command.livingroom_fan_direction
      data_template:
        direction: "{{ trigger.to_state.state }}"

- alias: Bedroom fan speed update
  trigger:
    platform: state
    entity_id: input_select.bedroom_fan_speed
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: shell_command.bedroom_fan_speed
      data_template:
        speed: "{{ trigger.to_state.state }}"

- alias: Bedroom fan direction update
  trigger:
    platform: state
    entity_id: input_select.bedroom_fan_direction
  action:
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: shell_command.bedroom_fan_direction
      data_template:
        direction: "{{ trigger.to_state.state }}"


- alias: "Bedroom climate turned on"
  trigger:
    - platform: state
      entity_id: climate.bedroom
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fan_mode
        option: 'off'

- alias: "Bedroom window open"
  trigger:
    - platform: time_pattern
      minutes: "/15"
    - platform: state
      entity_id: input_boolean.bedroom_window
      to: 'on'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'on'
      for:
        minutes: 2
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.fan_mode
          state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fan_mode
        option: 'off'

- alias: "Bedroom door open and window open"
  trigger:
    - platform: time_pattern
      minutes: "/15"
    - platform: state
      entity_id: input_boolean.bedroom_door
      to: 'on'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_door
      state: 'on'
      for:
        minutes: 2
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'on'
      for:
        minutes: 2
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.fan_mode
          state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fan_mode
        option: 'off'

- alias: "Bedroom window closed"
  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_window
      to: 'off'
  condition:
    - condition: state
      entity_id: input_select.fan_mode
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fan_mode
        option: 'default'



# - alias: "Bedroom door open and window closed"
#   trigger:
#     - platform: state
#       entity_id: input_boolean.bedroom_door
#       to: 'on'
#       for:
#         minutes: 5
#   condition:
#     - condition: state
#       entity_id: input_boolean.bedroom_door
#       state: 'on'
#       for:
#         minutes: 2
#     - condition: state
#       entity_id: input_boolean.bedroom_window
#       state: 'off'
#       for:
#         minutes: 2
#     - condition: state
#       entity_id: input_select.fan_mode
#       state: 'off'
#   action:
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.fan_mode
#         option: 'default'

# - alias: "Bedroom door closed"
#   trigger:
#     - platform: time_pattern
#       minutes: "/15"
#     - platform: state
#       entity_id: input_boolean.bedroom_door
#       to: 'off'
#       for:
#         minutes: 5
#   condition:
#     - condition: state
#       entity_id: input_boolean.bedroom_door
#       state: 'off'
#       for:
#         minutes: 2
#     - condition: state
#       entity_id: switch.livingroom_fan
#       state: 'off'
#   action:
#     - service: timer.start
#       entity_id: timer.fan_power_timer
#     - service: switch.turn_on
#       entity_id: switch.livingroom_fan



- alias: "Bedroom set default sleep mode"
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      above: 18
      below: 21
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'off'
    - condition: state
      entity_id: timer.fan_direction_timer
      state: idle
    - condition: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      above: 18
      below: 21
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fan_mode
        option: 'sleep'

- alias: "Bedroom warm when sleeping"
  trigger:
    - platform: time_pattern
      minutes: "/30"
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      above: 21
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'off'
    - condition: state
      entity_id: timer.fan_direction_timer
      state: idle
    - condition: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      above: 21
    - condition: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      above: sensor.netatmo_ewaldsvej_kokken_outdoor_temperature
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fan_mode
        option: 'sleep warm'

- alias: "Bedroom cold when sleeping"
  trigger:
    - platform: time_pattern
      minutes: "/30"
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      below: 18
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'off'
    - condition: state
      entity_id: timer.fan_direction_timer
      state: idle
    - condition: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      below: 18
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.fan_mode
        option: 'sleep cold'
