- alias: "Increase airflow via fans"
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
      above: 1500
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kokken_co2
      above: 1500
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
      above: 45
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'out'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_direction
        option: 'in'
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '02'

- alias: "Night setting for fans"
  trigger:
    - platform: state
      entity_id: input_boolean.sleep
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
      below: 1300
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'out'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_direction
        option: 'in'
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '01'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_speed
        option: '01'

- alias: "Normalize fans"
  trigger:
    - platform: state
      entity_id: input_boolean.sleep
      to: 'off'
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
      below: 1300
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kokken_co2
      below: 1300
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
      below: 40
    - platform: time_pattern
      minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
      below: 1300
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'alternating'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_direction
        option: 'alternating'
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '01'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_speed
        option: '01'
