- alias: Set Livingroom fan speed
  trigger:
    platform: state
    entity_id: sensor.livingroom_fan_speed
  action:
    service: input_select.select_option
    entity_id: input_select.livingroom_fan_speed
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Livingroom fan direction
  trigger:
    platform: state
    entity_id: sensor.livingroom_fan_direction
  action:
    service: input_select.select_option
    entity_id: input_select.livingroom_fan_direction
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Bedroom fan speed
  trigger:
    platform: state
    entity_id: sensor.bedroom_fan_speed
  action:
    service: input_select.select_option
    entity_id: input_select.bedroom_fan_speed
    data_template:
      option: "{{ trigger.to_state.state }}"

- alias: Set Bedroom fan direction
  trigger:
    platform: state
    entity_id: sensor.bedroom_fan_direction
  action:
    service: input_select.select_option
    entity_id: input_select.bedroom_fan_direction
    data_template:
      option: "{{ trigger.to_state.state }}"


- alias: Livingroom fan speed update
  trigger:
    platform: state
    entity_id: input_select.livingroom_fan_speed
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: shell_command.livingroom_fan_speed
      data_template:
        speed: "{{ trigger.to_state.state }}"

- alias: Livingroom fan direction update
  trigger:
    platform: state
    entity_id: input_select.livingroom_fan_direction
  action:
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: shell_command.livingroom_fan_direction
      data_template:
        direction: "{{ trigger.to_state.state }}"

- alias: Bedroom fan speed update
  trigger:
    platform: state
    entity_id: input_select.bedroom_fan_speed
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: shell_command.bedroom_fan_speed
      data_template:
        speed: "{{ trigger.to_state.state }}"

- alias: Bedroom fan direction update
  trigger:
    platform: state
    entity_id: input_select.bedroom_fan_direction
  action:
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: shell_command.bedroom_fan_direction
      data_template:
        direction: "{{ trigger.to_state.state }}"


- alias: "Bedroom window closed"
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: state
      entity_id: input_boolean.bedroom_window
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'off'
      for:
        minutes: 1
    - condition: or
      conditions:
        - condition: state
          entity_id: switch.bedroom_fan
          state: 'off'
        - condition: state
          entity_id: switch.livingroom_fan
          state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.bedroom_fan
    - service: switch.turn_on
      entity_id: switch.livingroom_fan

- alias: "Bedroom window open"
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: state
      entity_id: input_boolean.bedroom_window
      to: 'on'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'on'
      for:
        minutes: 1
    - condition: state
      entity_id: switch.bedroom_fan
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.bedroom_fan

- alias: "Bedroom door open and window closed"
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: state
      entity_id: input_boolean.bedroom_door
      to: 'on'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_door
      state: 'on'
      for:
        minutes: 1
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'off'
      for:
        minutes: 1
    - condition: state
      entity_id: switch.livingroom_fan
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.livingroom_fan

- alias: "Bedroom door open and window open"
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: state
      entity_id: input_boolean.bedroom_door
      to: 'on'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_door
      state: 'on'
      for:
        minutes: 1
    - condition: state
      entity_id: input_boolean.bedroom_window
      state: 'on'
      for:
        minutes: 1
    - condition: state
      entity_id: switch.livingroom_fan
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.livingroom_fan

- alias: "Bedroom door closed"
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: state
      entity_id: input_boolean.bedroom_door
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_door
      state: 'off'
      for:
        minutes: 1
    - condition: state
      entity_id: switch.livingroom_fan
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.livingroom_fan
