- alias: "Fan direction controller out"
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      above: 20
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
      above: 1500
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
      above: 45
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.fan_direction_timer
  condition:
    - condition: state
      entity_id: timer.fan_direction_timer
      state: finished
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.netatmo_ewaldsvej_kokken_outdoor_temperature
          above: 20
        - condition: numeric_state
          entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
          above: 1500
        - condition: numeric_state
          entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
          above: 45    
  action:
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'out'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_direction
        option: 'in'


- alias: "Fan direction controller in"
  trigger:
    - platform: time_pattern
      minutes: "/1"
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.fan_direction_timer
  condition:
    - condition: state
      entity_id: timer.fan_direction_timer
      state: finished
    - condition: or
      conditions:
        - condition: numeric_state
          entity_id: sensor.netatmo_ewaldsvej_kokken_outdoor_temperature
          above: 20
        - condition: template
          data_template: {{ sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature > sensor.netatmo_ewaldsvej_kokken_outdoor_temperature }}
        - condition: numeric_state
          entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
          below: 40
  action:
    - service: timer.start
      entity_id: timer.fan_direction_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_direction
        option: 'in'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_direction
        option: 'out'


- alias: "Fan speed controller 1"
  trigger:
    - platform: state
      entity_id: input_boolean.sleep
      to: 'on'
    - platform: time_pattern
      minutes: "/10"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: timer.fan_speed_timer
          state: finished
        - condition: state
          entity_id: timer.sleep
          state: finished
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '01'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_speed
        option: '01'


- alias: "Fan speed controller 2"
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
      above: 1500
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
      above: 45
  condition:
    - condition: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      above: 20
      below: 23
    - condition: template
      data_template: {{ sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature > sensor.netatmo_ewaldsvej_kokken_outdoor_temperature }}
    - condition: or
      conditions:
        - condition: state
          entity_id: timer.fan_speed_timer
          state: finished
        - condition: state
          entity_id: timer.sleep
          state: finished
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '02'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_speed
        option: '02'


- alias: "Fan speed controller 3"
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
      above: 1500
    - platform: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
      above: 55
  condition:
    - condition: numeric_state
      entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature
      above: 23
    - condition: template
      data_template: {{ sensor.netatmo_ewaldsvej_kitchen_bedroom_temperature > sensor.netatmo_ewaldsvej_kokken_outdoor_temperature }}
    - condition: or
      conditions:
        - condition: state
          entity_id: timer.fan_speed_timer
          state: finished
        - condition: state
          entity_id: timer.sleep
          state: finished
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '03'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_speed
        option: '03'


- alias: "Fan speed controller 1 night mode"
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.office_motion_sensor_1_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'on'
  action:
    - service: timer.start
      entity_id: timer.fan_speed_timer
    - service: input_select.select_option
      data:
        entity_id: input_select.bedroom_fan_speed
        option: '01'
    - service: input_select.select_option
      data:
        entity_id: input_select.livingroom_fan_speed
        option: '01'






# - alias: "Increase airflow via fans"
#   trigger:
#     - platform: numeric_state
#       entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
#       above: 1500
#     - platform: numeric_state
#       entity_id: sensor.netatmo_ewaldsvej_kokken_co2
#       above: 1500
#     - platform: numeric_state
#       entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
#       above: 45
#   action:
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.bedroom_fan_direction
#         option: 'out'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.livingroom_fan_direction
#         option: 'in'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.bedroom_fan_speed
#         option: '02'

# - alias: "Night setting for fans"
#   trigger:
#     - platform: state
#       entity_id: input_boolean.sleep
#       to: 'on'
#   condition:
#     - condition: numeric_state
#       entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
#       below: 1300
#   action:
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.bedroom_fan_direction
#         option: 'out'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.livingroom_fan_direction
#         option: 'in'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.bedroom_fan_speed
#         option: '01'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.livingroom_fan_speed
#         option: '01'

# - alias: "Normalize fans"
#   trigger:
#     - platform: state
#       entity_id: input_boolean.sleep
#       to: 'off'
#     - platform: numeric_state
#       entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
#       below: 1300
#     - platform: numeric_state
#       entity_id: sensor.netatmo_ewaldsvej_kokken_co2
#       below: 1300
#     - platform: numeric_state
#       entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_humidity
#       below: 40
#     - platform: time_pattern
#       minutes: 5
#   condition:
#     - condition: state
#       entity_id: input_boolean.sleep
#       state: 'off'
#     - condition: numeric_state
#       entity_id: sensor.netatmo_ewaldsvej_kitchen_bedroom_co2
#       below: 1300
#   action:
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.bedroom_fan_direction
#         option: 'alternating'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.livingroom_fan_direction
#         option: 'alternating'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.bedroom_fan_speed
#         option: '01'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.livingroom_fan_speed
#         option: '01'

# - alias: "Reset fans in night mode"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.kitchen_motion_sensor_1_motion
#       to: 'on'
#     - platform: state
#       entity_id: binary_sensor.office_motion_sensor_1_motion
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: input_boolean.sleep
#       state: 'on'
#   action:
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.bedroom_fan_direction
#         option: 'out'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.livingroom_fan_direction
#         option: 'in'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.bedroom_fan_speed
#         option: '01'
#     - service: input_select.select_option
#       data:
#         entity_id: input_select.livingroom_fan_speed
#         option: '01'
