- alias: "Henrik is Home"
  trigger:
    # - platform: zone
    #   entity_id: device_tracker.henrik_nicolaisens_iphone
    #   zone: zone.home
    #   event: enter
    - platform: state
      entity_id: person.henrik_nicolaisen
      to: 'home'
    #- platform: event
    #  event_type: deconz_event
    #  event_data:
    #    id: cinema_switch
    #    event: 1002
    #- platform: event
    #  event_type: deconz_event
    #  event_data:
    #    id: office_remote_control
    #    event: 1002
  action:
    - service: script.mode_home
