- alias: "Kitchen lights timer started"
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.kitchen_lights
    - platform: event
      event_type: timer.restarted
      event_data:
        entity_id: timer.kitchen_lights
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
    - condition: state
      entity_id: binary_sensor.daylight_kitchen
      state: 'off'
  action:
    - service: light.turn_on
      data:
        brightness: 255
        entity_id:
          - light.kitchen_lights

- alias: "Kitchen enought light detected"
  trigger:
    - platform: state
      entity_id: binary_sensor.daylight_kitchen
      to: 'on'
      for:
        minutes: 5
  action:
    service: timer.cancel
    entity_id:
      - timer.kitchen_lights

- alias: "Kitchen lights timer done"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_lights
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.kitchen_lights

- alias: "Motion in Kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.kitchen_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights
    - service: timer.start
      entity_id: timer.office_lights

- alias: "Motion in Kitchen (timer)"
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_motion_sensor_1_motion
        state: 'on'
      - condition: state
        entity_id: input_boolean.kitchen_motion
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights
    - service: timer.start
      entity_id: timer.office_lights


- alias: "Office lights timer started"
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.office_lights
    - platform: event
      event_type: timer.restarted
      event_data:
        entity_id: timer.office_lights
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
    - condition: state
      entity_id: binary_sensor.daylight_office
      state: 'off'
  action:
    - service: light.turn_on
      data:
        brightness: 255
        entity_id:
          - light.office_lights
          - light.living_room_lights
    - service: hue.hue_activate_scene
      data:
        group_name: "Cinema"
        scene_name: "Hass"

- alias: "Office enought light detected"
  trigger:
    - platform: state
      entity_id: binary_sensor.daylight_office
      to: 'on'
      for:
        minutes: 5
  action:
    service: timer.cancel
    entity_id:
      - timer.office_lights

- alias: "Office lights timer done"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.office_lights
  condition:
    - condition: state
      entity_id: binary_sensor.daylight_office
      state: 'on'
      for:
        minutes: 5
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.office_lights
        - light.cinema_lights
        - light.living_room_lights

- alias: "Motion in Office"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.office_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.office_lights
    - service: timer.start
      entity_id: timer.kitchen_lights

- alias: "Motion in Office (timer)"
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.office_motion_sensor_1_motion
        state: 'on'
      - condition: state
        entity_id: input_boolean.office_motion
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights
    - service: timer.start
      entity_id: timer.office_lights


- alias: "Bedroom lights timer started"
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.bedroom_lights
    - platform: event
      event_type: timer.restarted
      event_data:
        entity_id: timer.bedroom_lights
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
    - condition: state
      entity_id: binary_sensor.daylight_bedroom
      state: 'off'
  action:
    - service: light.turn_on
      data:
        brightness: 255
        entity_id:
          - light.bedroom_lights

- alias: "Bedroom lights timer done"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bedroom_lights
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.bedroom_lights

- alias: "Motion in Bedroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.bedroom_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.bedroom_lights

- alias: "Motion in Bedroom (timer)"
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.bedroom_motion_sensor_1_motion
        state: 'on'
      - condition: state
        entity_id: input_boolean.bedroom_motion
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.bedroom_lights


- alias: "Entrance lights timer started"
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.entrance_lights
    - platform: event
      event_type: timer.restarted
      event_data:
        entity_id: timer.entrance_lights
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
  action:
    - service: light.turn_on
      data:
        brightness: 255
        entity_id:
          - light.entrance_lights

- alias: "Entrance lights timer done"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.entrance_lights
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.entrance_lights

- alias: "Motion in Entrance"
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entrance_motion_sensor_2_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.entrance_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.entrance_lights

- alias: "Motion in Entrance (timer)"
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.entrance_motion_sensor_1_motion
        state: 'on'
      - condition: state
        entity_id: binary_sensor.entrance_motion_sensor_2_motion
        state: 'on'
      - condition: state
        entity_id: input_boolean.entrance_motion
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.entrance_lights

- alias: "Outside light turn on"
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.outside_lights

- alias: "Outside light turn off"
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.outside_lights
