- alias: "Kitchen lights timer started"
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.kitchen_lights
    - platform: event
      event_type: timer.restarted
      event_data:
        entity_id: timer.kitchen_lights
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.kitchen_motion_sensor_1_light_level
      below: 300
  action:
    - service: light.turn_on
      data:
        brightness: 255
        entity_id:
          - light.kitchen_lights
          - light.living_room_table
          - light.artemide_lamp
    - service: hue.hue_activate_scene
      data:
        group_name: "Cinema"
        scene_name: "Dimmed"

- alias: "Kitchen lights timer done"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_lights
  condition:
    - condition: state
      entity_id: binary_sensor.kitchen_motion_sensor_1
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.kitchen_lights

- alias: "Motion in Kitchen"
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor_1
      to: 'on'
    - platform: state
      entity_id: input_boolean.kitchen_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights

# - alias: "Motion stopped in Kitchen"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.kitchen_motion_sensor_1
#       to: 'off'
#       for:
#         minutes: 30
#   condition:
#     - condition: state
#       entity_id: timer.kitchen_lights
#       state: 'idle'
#   action:
#     service: timer.finish
#     entity_id: timer.kitchen_lights

- alias: "Motion in Office"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_sensor_1
      to: 'on'
    - platform: state
      entity_id: input_boolean.office_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights

# - alias: "Motion stopped in Office"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.office_motion_sensor_1
#       to: 'off'
#       for:
#         minutes: 30
#   condition:
#     - condition: state
#       entity_id: timer.kitchen_lights
#       state: 'idle'
#   action:
#     service: timer.finish
#     entity_id: timer.kitchen_lights


- alias: "Bedroom lights timer started"
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.bedroom_lights
    - platform: event
      event_type: timer.restarted
      event_data:
        entity_id: timer.bedroom_lights
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.bedroom_motion_sensor_1_light_level
      below: 300
  action:
    - service: light.turn_on
      data:
        brightness: 255
        entity_id:
          - light.bedroom_lights

- alias: "Bedroom lights timer done"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.bedroom_lights
  condition:
    - condition: state
      entity_id: binary_sensor.bedroom_motion_sensor_1
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.bedroom_lights

- alias: "Motion in Bedroom"
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor_1
      to: 'on'
    - platform: state
      entity_id: input_boolean.bedroom_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.bedroom_lights

# - alias: "Motion stopped in Bedroom"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.bedroom_motion_sensor_1
#       to: 'off'
#       for:
#         minutes: 30
#   condition:
#     - condition: state
#       entity_id: timer.bedroom_lights
#       state: 'idle'
#   action:
#     service: timer.finish
#     entity_id: timer.bedroom_lights


- alias: "Entrance lights timer started"
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.entrance_lights
    - platform: event
      event_type: timer.restarted
      event_data:
        entity_id: timer.entrance_lights
  condition:
    - condition: state
      entity_id: input_boolean.sleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.home
      state: 'on'
  action:
    - service: light.turn_on
      data:
        brightness: 255
        entity_id:
          - light.entrance_lights
          - light.kitchen_lights

- alias: "Entrance lights timer done"
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.entrance_lights
  condition:
    - condition: state
      entity_id: binary_sensor.entrance_motion_sensor_1
      state: 'off'
    - condition: state
      entity_id: binary_sensor.entrance_motion_sensor_2
      state: 'off'
  action:
    service: light.turn_off
    data:
      entity_id: light.entrance_lights

- alias: "Motion in Entrance"
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_motion_sensor_1
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entrance_motion_sensor_2
      to: 'on'
    - platform: state
      entity_id: input_boolean.entrance_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id:
        - timer.entrance_lights
        - timer.kitchen_lights

# - alias: "Motion stopped in Entrance"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.entrance_motion_sensor_1
#       to: 'off'
#       for:
#         minutes: 30
#     - platform: state
#       entity_id: binary_sensor.entrance_motion_sensor_2
#       to: 'off'
#       for:
#         minutes: 30
#   condition:
#     - condition: state
#       entity_id: timer.entrance_lights
#       state: 'idle'
#   action:
#     service: timer.finish
#     entity_id: timer.entrance_lights
