- alias: "Motion in Kitchen"
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.kitchen_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights
    - service: timer.start
      entity_id: timer.office_lights

- alias: "Motion in Kitchen (timer)"
  mode: queued
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.kitchen_motion_sensor_1_motion
        state: 'on'
      - condition: state
        entity_id: input_boolean.kitchen_motion
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights
    - service: timer.start
      entity_id: timer.office_lights


- alias: "Motion in Office"
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.office_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.office_lights
    - service: timer.start
      entity_id: timer.kitchen_lights

- alias: "Motion in Office (timer)"
  mode: queued
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.office_motion_sensor_1_motion
          state: 'on'
        - condition: state
          entity_id: input_boolean.office_motion
          state: 'on'
  action:
    - service: timer.start
      entity_id: timer.kitchen_lights
    - service: timer.start
      entity_id: timer.office_lights


- alias: "Motion in Bedroom"
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.bedroom_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.bedroom_lights

- alias: "Motion in Bedroom (timer)"
  mode: queued
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.bedroom_motion
          state: 'on'
        - condition: state
          entity_id: binary_sensor.bedroom_motion_sensor_1_motion
          state: 'on'
  action:
    - service: timer.start
      entity_id: timer.bedroom_lights


- alias: "Motion in Entrance"
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_motion_sensor_1_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.entrance_motion_sensor_2_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.entrance_motion
      to: 'on'
  action:
    - service: timer.start
      entity_id: timer.entrance_lights

- alias: "Motion in Entrance (timer)"
  mode: queued
  trigger:
    - platform: time_pattern
      minutes: "/1"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.entrance_motion_sensor_1_motion
        state: 'on'
      - condition: state
        entity_id: binary_sensor.entrance_motion_sensor_2_motion
        state: 'on'
      - condition: state
        entity_id: input_boolean.entrance_motion
        state: 'on'
  action:
    - service: timer.start
      entity_id: timer.entrance_lights
