- alias: Fan mode set on
  trigger:
    - platform: state
      entity_id: input_select.fan_mode
      to: 'on'
    - platform: state
      entity_id: input_select.fan_mode
      from: 'off'
      to: 'auto'
  action:
    - service: script.turn_on
      entity_id: script.servers_on

- alias: Fan mode set off
  trigger:
    - platform: state
      entity_id: input_select.fan_mode
      to: 'off'
    - platform: state
      entity_id: input_select.fan_mode
      from: 'on'
      to: 'auto'
  action:
    - service: script.turn_on
      entity_id: script.servers_off
