# - alias: "Apple TV is playing"
#   trigger:
#     - platform: state
#       entity_id: media_player.apple_tv_2
#       to: 'playing'
#       from: 'idle'
#     - platform: state
#       entity_id: media_player.apple_tv_2
#       to: 'playing'
#       from: 'off'
#     - platform: state
#       entity_id: media_player.apple_tv_2
#       to: 'playing'
#       from: 'paused'
#   action:
#     service: scene.turn_on
#     entity_id: scene.kitchen_off

# - alias: "Apple TV is paused"
#   trigger:
#     - platform: state
#       entity_id: media_player.apple_tv_2
#       to: 'paused'
#       from: 'playing'
#       for:
#         seconds: 15
#   action:
#     service: scene.turn_on
#     entity_id: scene.kitchen_on
#
# - alias: "Apple TV is idle"
#   trigger:
#     - platform: state
#       entity_id: media_player.apple_tv_2
#       to: 'idle'
#       from: 'playing'
#     - platform: state
#       entity_id: media_player.apple_tv_2
#       to: 'idle'
#       from: 'paused'
#   action:
#     service: scene.turn_on
#     entity_id: scene.kitchen_on

# - alias: "PS4 turned on"
#   trigger:
#     - platform: state
#       entity_id: media_player.playstation_4
#       to: 'playing'
#   action:
#     - service: media_player.select_source
#       data:
#         entity_id: media_player.denon_avr_x1300w
#         #source: 'Game'
#         source: 'TV Audio'
#     - service: media_player.select_sound_mode
#       data:
#         entity_id: media_player.denon_avr_x1300w
#         sound_mode: 'GAME'
#     - service: media_player.select_source
#       data:
#         entity_id: media_player.lg_oled
#         #source: 'HDMI2'
#         source: 'HDMI3'

# - alias: "PS4 turned off"
#   trigger:
#     - platform: state
#       entity_id: media_player.playstation_4
#       from: 'playing'
#       to: 'off'
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{% if is_state_attr('media_player.lg_oled', 'source', 'HDMI2') %}true{% endif %}"
#       - condition: template
#         value_template: "{% if is_state_attr('media_player.denon_avr_x1300w', 'source', 'Game') %}true{% endif %}"
#   action:
#     - service: media_player.select_source
#       data:
#         entity_id: media_player.denon_avr_x1300w
#         #source: 'Media Player'
#         source: 'TV Audio'
#     - service: media_player.select_sound_mode
#       data:
#         entity_id: media_player.denon_avr_x1300w
#         sound_mode: 'MOVIE'
#     - service: media_player.select_source
#       data:
#         entity_id: media_player.lg_oled
#         #source: 'HDMI2'
#         source: 'HDMI4'
#     - service: media_player.turn_on
#       entity_id: media_player.apple_tv

# - alias: "Nintendo Switch turned on"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.nintendo_switch
#       from: 'off'
#       to: 'on'
#   condition:
#     - condition: state
#       entity_id: binary_sensor.nintendo_switch
#       state: 'on'
#       for:
#         minutes: 1
#   action:
#     - service: media_player.select_source
#       data:
#         entity_id: media_player.denon_avr_x1300w
#         source: 'Switch'
#     - service: media_player.select_source
#       data:
#         entity_id: media_player.lg_oled
#         source: 'HDMI2'

# - alias: "Nintendo Switch turned off"
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.nintendo_switch
#       from: 'on'
#       to: 'off'
#   condition:
#     condition: and
#     conditions:
#       - condition: template
#         value_template: "{% if is_state_attr('media_player.lg_oled', 'source', 'HDMI2') %}true{% endif %}"
#       - condition: template
#         value_template: "{% if is_state_attr('media_player.denon_avr_x1300w', 'source', 'Switch') %}true{% endif %}"
#   action:
#     - service: media_player.select_source
#       data:
#         entity_id: media_player.denon_avr_x1300w
#         #source: 'Media Player'
#         source: 'TV Audio'
#     - service: media_player.select_sound_mode
#       data:
#         entity_id: media_player.denon_avr_x1300w
#         sound_mode: 'MOVIE'
#     - service: media_player.select_source
#       data:
#         entity_id: media_player.lg_oled
#         #source: 'HDMI2'
#         source: 'HDMI4'
#     - service: media_player.turn_on
#       entity_id: media_player.apple_tv

- alias: "TV app started"
  trigger:
    - platform: template
      value_template: "{% if not is_state_attr('media_player.lg_oled', 'source', 'HDMI2') %}true{% endif %}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: media_player.lg_oled
        state: 'playing'
      - condition: state
        entity_id: media_player.denon_avr_x1300w
        state: 'on'
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avr_x1300w
        source: 'TV Audio'
    - service: media_player.select_sound_mode
      data:
        entity_id: media_player.denon_avr_x1300w
        sound_mode: 'DTS SURROUND'

- alias: "Plex is playing"
  trigger:
    - platform: state
      entity_id: media_player.apple_tv_2
      to: 'playing'
  action:
    - service: media_player.select_source
      data:
        entity_id: media_player.denon_avr_x1300w
        #source: 'Media Player'
        source: 'TV Audio'
    - service: media_player.select_sound_mode
      data:
        entity_id: media_player.denon_avr_x1300w
        sound_mode: 'DTS SURROUND'
    - service: media_player.select_source
      data:
        entity_id: media_player.lg_oled
        #source: 'HDMI2'
        source: 'Apple TV'
